name: Build and deploy examples-vite dir to GitHub Pages

on:
  # Triggers when a Pull Request targeting 'main' is closed
  pull_request:
    types: [closed]
    branches:
      - main # Change to your default branch if different
    paths:
      - 'examples-vite/**'
  # Triggers a manual button in the GitHub Actions UI
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # Sets the default folder for ALL run steps in this job
    defaults:
      run:
        working-directory: ./examples-vite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        # 'npm install' obeys your package.json semantic version ranges
        # '--no-audit --no-fund' speeds up the build process
        # If want to restrict to package-lock.json, could use "npm ci"
        run: npm install --no-audit --no-fund

      - name: Extract sqljs WASM from node_modules
        run: npm run-script sql-install

      - name: Build site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './examples-vite/dist' # Vite outputs to 'dist' by default

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4